on:
  push:
    branches: [ dev ]
name: 🤘 FTP Deploy
jobs:
  web-deploy:
    name: 🔥 FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - name: ⚰️ Get latest code
      uses: actions/checkout@v2
    - name: 🩸 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.FTP_SERVER_DEV }}
        username: ${{ secrets.FTP_USERNAME_DEV }}
        password: ${{ secrets.FTP_PASSWORD_DEV }}
        server-dir: public_html/dev/
        exclude: "[.git/**, .git**, .git*/**, /.git*/**, .github/**, .github**, .github*/**, /.github*/**, **/LICENSE/**, **/README.md/**, **/SECURITY.md/**, **/src/**, **/package.json/**, **/webpack.config.js/**, **/node_module/**, **/.gitignore/**]"