name: Metrics
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
        - name: 🌇 GitHub Skyline 3D calendar
          if: ${{ success() || failure() }}
          uses: lowlighter/metrics@master
          with:
            filename: metrics.plugin.skyline.svg
            token: NOT_NEEDED
            plugin_skyline: yes
            plugin_skyline_year: 2020
            plugin_skyline_frames: 6
            plugin_skyline_quality: 1
            plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
            output_action: pull-request
            delay: 120
